In [1]:
import pandas as pd
from textblob import Word
import numpy as np
import re
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix

In [3]:
df_train = pd.read_csv('D:/News_Hackathon/Participants_Data_News_category/Data_Train.csv')

x=df_train['STORY'].tolist()
vect = TfidfVectorizer(stop_words='english')
X = vect.fit_transform(x).toarray()
y = df_train.iloc[:, 1].values

In [4]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=0)

print ("train size:", X_train.shape)
print ("test size:", X_test.shape)

train size: (6102, 32504)
test size: (1526, 32504)


In [7]:
%timeit
model = RandomForestClassifier(n_estimators=300, max_depth=150,n_jobs=-1)
model.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=150, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=300,
                       n_jobs=-1, oob_score=False, random_state=None, verbose=0,
                       warm_start=False)

In [8]:
y_pred = model.predict(X_test)
c_mat = confusion_matrix(y_test,y_pred)
acc = accuracy_score(y_test,y_pred)
print ("Confusion Matrix:\n", c_mat)
print ("Accuracy:\n", acc)
submission = pd.DataFrame({
        "SECTION": y_pred
    })
submission.to_csv('D:/News_Hackathon/Participants_Data_News_category/submission_news2.csv', encoding='utf-8', index=False)

Confusion Matrix:
 [[326  14   8   2]
 [  3 517  18   3]
 [  6   4 365   1]
 [  3  13  11 232]]
Accuracy:
 0.9436435124508519
