In [2]:
import pandas as pd
from textblob import Word
import numpy as np
import re
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix

In [35]:
df_train=pd.read_excel("E:/Datasets/PredictTheNews/Data_Train.xlsx")
x=df_train['STORY']
vect = TfidfVectorizer(stop_words='english', max_features=1000)
X = vect.fit_transform(x).toarray()
y = df_train.iloc[:, 1].values
X

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [36]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=0)

print ("train size:", X_train.shape)
print ("test size:", X_test.shape)

train size: (6102, 1000)
test size: (1526, 1000)


In [37]:
%timeit
model = RandomForestClassifier(n_estimators=300, max_depth=150,n_jobs=-1)
model.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=150, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=300,
                       n_jobs=-1, oob_score=False, random_state=None, verbose=0,
                       warm_start=False)

In [38]:
y_pred = model.predict(X_test)
c_mat = confusion_matrix(y_test,y_pred)
acc = accuracy_score(y_test,y_pred)
acc

0.9325032765399738

In [39]:
df_test=pd.read_excel("E:/Datasets/PredictTheNews/Data_Test.xlsx")

In [40]:
xt=df_test['STORY']
X_test_val = vect.fit_transform(xt).toarray()
X_test_val

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.31698976, 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [41]:
y_predict = model.predict(X_test_val)
y_predict

array([0, 2, 1, ..., 2, 1, 1], dtype=int64)

In [42]:
submission = pd.DataFrame({
        "SECTION": y_predict
    })
submission.to_csv('submission_news_satyam.csv', encoding='utf-8', index=False)